import { SEARCH_UPDATE } from '../actions/types'
import { assign } from 'lodash'

const INITIAL_STATE = {
    origin: "",
    destination: "",
    loading: false,
    stationsQuery: "",
    allStations: [
        "Abbesses",
        "Alésia",
        "Alexandre Dumas",
        "Alma-Marceau",
        "Anatole France",
        "Anvers",
        "Argentine",
        "Arts et Métiers",
        "Asnières-Gennevilliers-Les Courtilles",
        "Assemblée nationale",
        "Aubervilliers-Front Populaire",
        "Aubervilliers-Pantin-Quatre Chemins",
        "Avenue Émile Zola",
        "Avron",
        "Balard",
        "Barbès-Rochechouart",
        "Basilique de Saint-Denis",
        "Bastille",
        "Bel-Air",
        "Belleville",
        "Bérault",
        "Bercy",
        "Bibliothèque François Mitterrand",
        "Billancourt",
        "Bir-Hakeim",
        "Blanche",
        "Bobigny-Pablo Picasso",
        "Bobigny-Pantin-Raymond Queneau",
        "Boissière",
        "Bolivar",
        "Bonne Nouvelle",
        "Botzaris",
        "Boucicaut",
        "Boulogne-Jean Jaurès",
        "Boulogne-Pont de Saint-Cloud",
        "Bourse",
        "Bréguet-Sabin",
        "Brochant",
        "Buttes Chaumont",
        "Buzenval",
        "Cadet",
        "Cambronne",
        "Campo-Formio",
        "Cardinal Lemoine",
        "Carrefour Pleyel",
        "Censier-Daubenton",
        "Champs-Élysées-Clemenceau",
        "Chardon-Lagache",
        "Charenton-Écoles",
        "Charles de Gaulle-Étoile",
        "Charles Michels",
        "Charonne",
        "Château d'Eau",
        "Château de Vincennes",
        "Château Rouge",
        "Château-Landon",
        "Châtelet",
        "Châtillon-Montrouge",
        "Chaussée d'Antin-La Fayette",
        "Chemin Vert",
        "Chevaleret",
        "Cité",
        "Cluny-La Sorbonne",
        "Colonel Fabien",
        "Commerce",
        "Concorde",
        "Convention",
        "Corentin Cariou",
        "Corentin Celton",
        "Corvisart",
        "Cour Saint-Émilion",
        "Courcelles",
        "Couronnes",
        "Créteil-L'Échat",
        "Créteil-Pointe du Lac",
        "Créteil-Préfecture",
        "Créteil-Université",
        "Crimée",
        "Croix de Chavaux",
        "Danube",
        "Daumesnil",
        "Denfert-Rochereau",
        "Dugommier",
        "Dupleix",
        "Duroc",
        "École Militaire",
        "École Vétérinaire de Maisons-Alfort",
        "Edgar Quinet",
        "Eglise d'Auteuil",
        "Église de Pantin",
        "Esplanade de la Défense",
        "Étienne Marcel",
        "Europe",
        "Exelmans",
        "Faidherbe-Chaligny",
        "Falguière",
        "Félix Faure",
        "Filles du Calvaire",
        "Fort d'Aubervilliers",
        "Franklin D. Roosevelt",
        "Gabriel Péri",
        "Gaîté",
        "Gallieni",
        "Gambetta",
        "Gare d'Austerlitz",
        "Gare de l'Est",
        "Gare de Lyon",
        "Gare du Nord",
        "Garibaldi",
        "George V",
        "Glacière",
        "Goncourt",
        "Grands Boulevards",
        "Guy Môquet",
        "Havre-Caumartin",
        "Hoche",
        "Hôtel de Ville",
        "Iéna",
        "Invalides",
        "Jacques Bonsergent",
        "Jasmin",
        "Jaurès",
        "Javel-André Citroën",
        "Jourdain",
        "Jules Joffrin",
        "Jussieu",
        "Kléber",
        "La Chapelle",
        "La Courneuve-8 Mai 1945",
        "La Défense-Grande Arche",
        "La Fourche",
        "La Motte-Picquet-Grenelle",
        "La Muette",
        "La Tour-Maubourg",
        "Lamarck-Caulaincourt",
        "Laumière",
        "Le Kremlin-Bicêtre",
        "Le Peletier",
        "Ledru-Rollin",
        "Les Agnettes",
        "Les Gobelins",
        "Les Halles",
        "Les Sablons",
        "Liberté",
        "Liège",
        "Louis Blanc",
        "Louise Michel",
        "Lourmel",
        "Louvre-Rivoli",
        "Mabillon",
        "Madeleine",
        "Mairie d'Issy",
        "Mairie d'Ivry",
        "Mairie de Clichy",
        "Mairie de Montreuil",
        "Mairie de Montrouge",
        "Mairie de Saint-Ouen",
        "Mairie des Lilas",
        "Maison Blanche",
        "Maisons-Alfort-Les Juilliottes",
        "Maisons-Alfort-Stade",
        "Malakoff-Plateau de Vanves",
        "Malakoff-Rue Étienne Dolet",
        "Malesherbes",
        "Maraîchers",
        "Marcadet-Poissonniers",
        "Marcel Sembat",
        "Marx Dormoy",
        "Maubert-Mutualité",
        "Ménilmontant",
        "Michel Bizot",
        "Michel-Ange-Auteuil",
        "Michel-Ange-Molitor",
        "Mirabeau",
        "Miromesnil",
        "Monceau",
        "Montgallet",
        "Montparnasse-Bienvenüe",
        "Mouton-Duvernet",
        "Nation",
        "Nationale",
        "Notre-Dame-de-Lorette",
        "Notre-Dame-des-Champs",
        "Oberkampf",
        "Odéon",
        "Olympiades",
        "Opéra",
        "Ourcq",
        "Palais Royal-Musée du Louvre",
        "Parmentier",
        "Passy",
        "Pasteur",
        "Pelleport",
        "Père Lachaise",
        "Pereire",
        "Pernety",
        "Philippe Auguste",
        "Picpus",
        "Pierre et Marie Curie",
        "Pigalle",
        "Place d'Italie",
        "Place de Clichy",
        "Place des Fêtes",
        "Place Monge",
        "Plaisance",
        "Poissonnière",
        "Pont de Levallois-Bécon",
        "Pont de Neuilly",
        "Pont de Sèvres",
        "Pont Marie",
        "Pont Neuf",
        "Porte d'Auteuil",
        "Porte d'Italie",
        "Porte d'Ivry",
        "Porte d'Orléans",
        "Porte Dauphine",
        "Porte de Bagnolet",
        "Porte de Champerret",
        "Porte de Charenton",
        "Porte de Choisy",
        "Porte de Clichy",
        "Porte de Clignancourt",
        "Porte de la Chapelle",
        "Porte de la Villette",
        "Porte de Montreuil",
        "Porte de Pantin",
        "Porte de Saint-Cloud",
        "Porte de Saint-Ouen",
        "Porte de Vanves",
        "Porte de Versailles",
        "Porte de Vincennes",
        "Porte des Lilas",
        "Porte Dorée",
        "Porte Maillot",
        "Pré Saint-Gervais",
        "Pyramides",
        "Pyrénées",
        "Quai de la Gare",
        "Quai de la Rapée",
        "Quatre-Septembre",
        "Rambuteau",
        "Ranelagh",
        "Raspail",
        "Réaumur-Sébastopol",
        "Rennes",
        "République",
        "Reuilly-Diderot",
        "Richard-Lenoir",
        "Richelieu-Drouot",
        "Riquet",
        "Robespierre",
        "Rome",
        "Rue de la Pompe",
        "Rue des Boulets",
        "Rue du Bac",
        "Rue Saint-Maur",
        "Saint-Ambroise",
        "Saint-Augustin",
        "Saint-Denis-Porte de Paris",
        "Saint-Denis-Université",
        "Saint-Fargeau",
        "Saint-François-Xavier",
        "Saint-Georges",
        "Saint-Germain-des-Prés",
        "Saint-Jacques",
        "Saint-Lazare",
        "Saint-Mandé",
        "Saint-Marcel",
        "Saint-Michel",
        "Saint-Paul",
        "Saint-Philippe du Roule",
        "Saint-Placide",
        "Saint-Sébastien-Froissart",
        "Saint-Sulpice",
        "Ségur",
        "Sentier",
        "Sèvres-Babylone",
        "Sèvres-Lecourbe",
        "Simplon",
        "Solférino",
        "Stalingrad",
        "Strasbourg-Saint-Denis",
        "Sully-Morland",
        "Télégraphe",
        "Temple",
        "Ternes",
        "Tolbiac",
        "Trinité-d'Estienne d'Orves",
        "Trocadéro",
        "Tuileries",
        "Vaneau",
        "Varenne",
        "Vaugirard",
        "Vavin",
        "Victor Hugo",
        "Villejuif — Louis Aragon",
        "Villejuif-Léo Lagrange",
        "Villejuif-Paul Vaillant-Couturier",
        "Villiers",
        "Volontaires",
        "Voltaire",
        "Wagram"
    ]
}

export default (state = INITIAL_STATE, action) => {
    switch (action.type) {
        case SEARCH_UPDATE:
            return assign({}, state, action.payload)
        default:
            return state
    }
}